[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
net = { path = "../../../" }
serde = "1.0.219"
serde_json = "1.0.140"
ts-rs = "10.1.0"
