// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JoinParams } from "./JoinParams";

export type ClientMessage = { "Join": JoinParams };
