// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerState = { position: [number, number, number], up: [number, number, number], rotate: [number, number, number, number], movement_state: string, };
