// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerState } from "./PlayerState";

export type ServerMessage = { "Update": { [key in number]?: PlayerState } } | { "PlayerJoined": number } | { "PlayerLeft": number };
